public class SubMerchantModel {
	
	private String subMerchantStreetAddress1;
    private String subMerchantStreetAddress2;
    private String subMerchantCity;
    private String subMerchantStateProvince;
    private String subMerchantPostalCode;
    private String subMerchantCountryCode;
    private String subMerchantAmexMid;
    private String subMerchantBankAccountNumber;
    private String subMerchantBankRoutingNumber;
    private String subMerchantCreateCredentials;
    private String subMerchantCustomerServiceNumber;
    private String subMerchantDiscoverConveyMid;
    private String subMerchantHardCodeBillingDescriptor;
    private String subMerchantMaxTransactionAmount;
    private String subMerchantMerchantCategoryCode;
    private String subMerchantMerchantName;
    private String subMerchantFirstName;
    private String subMerchantLastName;
    private String subMerchantEmailAddress;
    private String subMerchantPhone;
    private String subMerchantPspMerchantId;
    private String subMerchantUrl;
    private String subMerchanteCheckBillingDescriptor;
    private String subMerchanteCheckCompanyName;
    
    // Default values
    private String subMerchantStreetAddress1Default;
    private String subMerchantStreetAddress2Default;
    private String subMerchantCityDefault;
    private String subMerchantStateProvinceDefault;
    private String subMerchantPostalCodeDefault;
    private String subMerchantCountryCodeDefault;
    private String subMerchantAmexMidDefault;
    private String subMerchantBankAccountNumberDefault;
    private String subMerchantBankRoutingNumberDefault;
    private String subMerchantCreateCredentialsDefault;
    private String subMerchantCustomerServiceNumberDefault;
    private String subMerchantDiscoverConveyMidDefault;
    private String subMerchantHardCodeBillingDescriptorDefault;
    private String subMerchantMaxTransactionAmountDefault;
    private String subMerchantMerchantCategoryCodeDefault;
    private String subMerchantMerchantNameDefault;
    private String subMerchantFirstNameDefault;
    private String subMerchantLastNameDefault;
    private String subMerchantEmailAddressDefault;
    private String subMerchantPhoneDefault;
    private String subMerchantPspMerchantIdDefault;
    private String subMerchantUrlDefault;
    private String subMerchanteCheckBillingDescriptorDefault;
    private String subMerchanteCheckCompanyNameDefault;
    
    public String getSubMerchantStreetAddress1Default() {
        return subMerchantStreetAddress1Default;
    }
    public void setSubMerchantStreetAddress1Default(
            String subMerchantStreetAddress1Default) {
        this.subMerchantStreetAddress1Default = subMerchantStreetAddress1Default;
    }
    public String getSubMerchantStreetAddress2Default() {
        return subMerchantStreetAddress2Default;
    }
    public void setSubMerchantStreetAddress2Default(
            String subMerchantStreetAddress2Default) {
        this.subMerchantStreetAddress2Default = subMerchantStreetAddress2Default;
    }
    public String getSubMerchantCityDefault() {
        return subMerchantCityDefault;
    }
    public void setSubMerchantCityDefault(String subMerchantCityDefault) {
        this.subMerchantCityDefault = subMerchantCityDefault;
    }
    public String getSubMerchantStateProvinceDefault() {
        return subMerchantStateProvinceDefault;
    }
    public void setSubMerchantStateProvinceDefault(
            String subMerchantStateProvinceDefault) {
        this.subMerchantStateProvinceDefault = subMerchantStateProvinceDefault;
    }
    public String getSubMerchantPostalCodeDefault() {
        return subMerchantPostalCodeDefault;
    }
    public void setSubMerchantPostalCodeDefault(String subMerchantPostalCodeDefault) {
        this.subMerchantPostalCodeDefault = subMerchantPostalCodeDefault;
    }
    public String getSubMerchantCountryCodeDefault() {
        return subMerchantCountryCodeDefault;
    }
    public void setSubMerchantCountryCodeDefault(
            String subMerchantCountryCodeDefault) {
        this.subMerchantCountryCodeDefault = subMerchantCountryCodeDefault;
    }
    public String getSubMerchantAmexMidDefault() {
        return subMerchantAmexMidDefault;
    }
    public void setSubMerchantAmexMidDefault(String subMerchantAmexMidDefault) {
        this.subMerchantAmexMidDefault = subMerchantAmexMidDefault;
    }
    public String getSubMerchantBankAccountNumberDefault() {
        return subMerchantBankAccountNumberDefault;
    }
    public void setSubMerchantBankAccountNumberDefault(
            String subMerchantBankAccountNumberDefault) {
        this.subMerchantBankAccountNumberDefault = subMerchantBankAccountNumberDefault;
    }
    public String getSubMerchantBankRoutingNumberDefault() {
        return subMerchantBankRoutingNumberDefault;
    }
    public void setSubMerchantBankRoutingNumberDefault(
            String subMerchantBankRoutingNumberDefault) {
        this.subMerchantBankRoutingNumberDefault = subMerchantBankRoutingNumberDefault;
    }
    public String getSubMerchantCreateCredentialsDefault() {
        return subMerchantCreateCredentialsDefault;
    }
    public void setSubMerchantCreateCredentialsDefault(
            String subMerchantCreateCredentialsDefault) {
        this.subMerchantCreateCredentialsDefault = subMerchantCreateCredentialsDefault;
    }
    public String getSubMerchantCustomerServiceNumberDefault() {
        return subMerchantCustomerServiceNumberDefault;
    }
    public void setSubMerchantCustomerServiceNumberDefault(
            String subMerchantCustomerServiceNumberDefault) {
        this.subMerchantCustomerServiceNumberDefault = subMerchantCustomerServiceNumberDefault;
    }
    public String getSubMerchantDiscoverConveyMidDefault() {
        return subMerchantDiscoverConveyMidDefault;
    }
    public void setSubMerchantDiscoverConveyMidDefault(
            String subMerchantDiscoverConveyMidDefault) {
        this.subMerchantDiscoverConveyMidDefault = subMerchantDiscoverConveyMidDefault;
    }
    public String getSubMerchantHardCodeBillingDescriptorDefault() {
        return subMerchantHardCodeBillingDescriptorDefault;
    }
    public void setSubMerchantHardCodeBillingDescriptorDefault(
            String subMerchantHardCodeBillingDescriptorDefault) {
        this.subMerchantHardCodeBillingDescriptorDefault = subMerchantHardCodeBillingDescriptorDefault;
    }
    public String getSubMerchantMaxTransactionAmountDefault() {
        return subMerchantMaxTransactionAmountDefault;
    }
    public void setSubMerchantMaxTransactionAmountDefault(
            String subMerchantMaxTransactionAmountDefault) {
        this.subMerchantMaxTransactionAmountDefault = subMerchantMaxTransactionAmountDefault;
    }
    public String getSubMerchantMerchantCategoryCodeDefault() {
        return subMerchantMerchantCategoryCodeDefault;
    }
    public void setSubMerchantMerchantCategoryCodeDefault(
            String subMerchantMerchantCategoryCodeDefault) {
        this.subMerchantMerchantCategoryCodeDefault = subMerchantMerchantCategoryCodeDefault;
    }
    public String getSubMerchantMerchantNameDefault() {
        return subMerchantMerchantNameDefault;
    }
    public void setSubMerchantMerchantNameDefault(
            String subMerchantMerchantNameDefault) {
        this.subMerchantMerchantNameDefault = subMerchantMerchantNameDefault;
    }
    public String getSubMerchantFirstNameDefault() {
        return subMerchantFirstNameDefault;
    }
    public void setSubMerchantFirstNameDefault(String subMerchantFirstNameDefault) {
        this.subMerchantFirstNameDefault = subMerchantFirstNameDefault;
    }
    public String getSubMerchantLastNameDefault() {
        return subMerchantLastNameDefault;
    }
    public void setSubMerchantLastNameDefault(String subMerchantLastNameDefault) {
        this.subMerchantLastNameDefault = subMerchantLastNameDefault;
    }
    public String getSubMerchantEmailAddressDefault() {
        return subMerchantEmailAddressDefault;
    }
    public void setSubMerchantEmailAddressDefault(
            String subMerchantEmailAddressDefault) {
        this.subMerchantEmailAddressDefault = subMerchantEmailAddressDefault;
    }
    public String getSubMerchantPhoneDefault() {
        return subMerchantPhoneDefault;
    }
    public void setSubMerchantPhoneDefault(String subMerchantPhoneDefault) {
        this.subMerchantPhoneDefault = subMerchantPhoneDefault;
    }
    public String getSubMerchantPspMerchantIdDefault() {
        return subMerchantPspMerchantIdDefault;
    }
    public void setSubMerchantPspMerchantIdDefault(
            String subMerchantPspMerchantIdDefault) {
        this.subMerchantPspMerchantIdDefault = subMerchantPspMerchantIdDefault;
    }
    public String getSubMerchantUrlDefault() {
        return subMerchantUrlDefault;
    }
    public void setSubMerchantUrlDefault(String subMerchantUrlDefault) {
        this.subMerchantUrlDefault = subMerchantUrlDefault;
    }
    public String getSubMerchanteCheckBillingDescriptorDefault() {
        return subMerchanteCheckBillingDescriptorDefault;
    }
    public void setSubMerchanteCheckBillingDescriptorDefault(
            String subMerchanteCheckBillingDescriptorDefault) {
        this.subMerchanteCheckBillingDescriptorDefault = subMerchanteCheckBillingDescriptorDefault;
    }
    public String getSubMerchanteCheckCompanyNameDefault() {
        return subMerchanteCheckCompanyNameDefault;
    }
    public void setSubMerchanteCheckCompanyNameDefault(
            String subMerchanteCheckCompanyNameDefault) {
        this.subMerchanteCheckCompanyNameDefault = subMerchanteCheckCompanyNameDefault;
    }
    public String getSubMerchantStreetAddress1() {
        return subMerchantStreetAddress1;
    }
    public void setSubMerchantStreetAddress1(String subMerchantStreetAddress1) {
        this.subMerchantStreetAddress1 = subMerchantStreetAddress1;
    }
    public String getSubMerchantStreetAddress2() {
        return subMerchantStreetAddress2;
    }
    public void setSubMerchantStreetAddress2(String subMerchantStreetAddress2) {
        this.subMerchantStreetAddress2 = subMerchantStreetAddress2;
    }
    public String getSubMerchantCity() {
        return subMerchantCity;
    }
    public void setSubMerchantCity(String subMerchantCity) {
        this.subMerchantCity = subMerchantCity;
    }
    public String getSubMerchantStateProvince() {
        return subMerchantStateProvince;
    }
    public void setSubMerchantStateProvince(String subMerchantStateProvince) {
        this.subMerchantStateProvince = subMerchantStateProvince;
    }
    public String getSubMerchantPostalCode() {
        return subMerchantPostalCode;
    }
    public void setSubMerchantPostalCode(String subMerchantPostalCode) {
        this.subMerchantPostalCode = subMerchantPostalCode;
    }
    public String getSubMerchantCountryCode() {
        return subMerchantCountryCode;
    }
    public void setSubMerchantCountryCode(String subMerchantCountryCode) {
        this.subMerchantCountryCode = subMerchantCountryCode;
    }
    public String getSubMerchantAmexMid() {
        return subMerchantAmexMid;
    }
    public void setSubMerchantAmexMid(String subMerchantAmexMid) {
        this.subMerchantAmexMid = subMerchantAmexMid;
    }
    public String getSubMerchantBankAccountNumber() {
        return subMerchantBankAccountNumber;
    }
    public void setSubMerchantBankAccountNumber(String subMerchantBankAccountNumber) {
        this.subMerchantBankAccountNumber = subMerchantBankAccountNumber;
    }
    public String getSubMerchantBankRoutingNumber() {
        return subMerchantBankRoutingNumber;
    }
    public void setSubMerchantBankRoutingNumber(String subMerchantBankRoutingNumber) {
        this.subMerchantBankRoutingNumber = subMerchantBankRoutingNumber;
    }
    public String getSubMerchantCreateCredentials() {
        return subMerchantCreateCredentials;
    }
    public void setSubMerchantCreateCredentials(String subMerchantCreateCredentials) {
        this.subMerchantCreateCredentials = subMerchantCreateCredentials;
    }
    public String getSubMerchantCustomerServiceNumber() {
        return subMerchantCustomerServiceNumber;
    }
    public void setSubMerchantCustomerServiceNumber(
            String subMerchantCustomerServiceNumber) {
        this.subMerchantCustomerServiceNumber = subMerchantCustomerServiceNumber;
    }
    public String getSubMerchantDiscoverConveyMid() {
        return subMerchantDiscoverConveyMid;
    }
    public void setSubMerchantDiscoverConveyMid(String subMerchantDiscoverConveyMid) {
        this.subMerchantDiscoverConveyMid = subMerchantDiscoverConveyMid;
    }
    public String getSubMerchantHardCodeBillingDescriptor() {
        return subMerchantHardCodeBillingDescriptor;
    }
    public void setSubMerchantHardCodeBillingDescriptor(
            String subMerchantHardCodeBillingDescriptor) {
        this.subMerchantHardCodeBillingDescriptor = subMerchantHardCodeBillingDescriptor;
    }
    public String getSubMerchantMaxTransactionAmount() {
        return subMerchantMaxTransactionAmount;
    }
    public void setSubMerchantMaxTransactionAmount(
            String subMerchantMaxTransactionAmount) {
        this.subMerchantMaxTransactionAmount = subMerchantMaxTransactionAmount;
    }
    public String getSubMerchantMerchantCategoryCode() {
        return subMerchantMerchantCategoryCode;
    }
    public void setSubMerchantMerchantCategoryCode(
            String subMerchantMerchantCategoryCode) {
        this.subMerchantMerchantCategoryCode = subMerchantMerchantCategoryCode;
    }
    public String getSubMerchantMerchantName() {
        return subMerchantMerchantName;
    }
    public void setSubMerchantMerchantName(String subMerchantMerchantName) {
        this.subMerchantMerchantName = subMerchantMerchantName;
    }
    public String getSubMerchantFirstName() {
        return subMerchantFirstName;
    }
    public void setSubMerchantFirstName(String subMerchantFirstName) {
        this.subMerchantFirstName = subMerchantFirstName;
    }
    public String getSubMerchantLastName() {
        return subMerchantLastName;
    }
    public void setSubMerchantLastName(String subMerchantLastName) {
        this.subMerchantLastName = subMerchantLastName;
    }
    public String getSubMerchantEmailAddress() {
        return subMerchantEmailAddress;
    }
    public void setSubMerchantEmailAddress(String subMerchantEmailAddress) {
        this.subMerchantEmailAddress = subMerchantEmailAddress;
    }
    public String getSubMerchantPhone() {
        return subMerchantPhone;
    }
    public void setSubMerchantPhone(String subMerchantPhone) {
        this.subMerchantPhone = subMerchantPhone;
    }
    public String getSubMerchantPspMerchantId() {
        return subMerchantPspMerchantId;
    }
    public void setSubMerchantPspMerchantId(String subMerchantPspMerchantId) {
        this.subMerchantPspMerchantId = subMerchantPspMerchantId;
    }
    public String getSubMerchantUrl() {
        return subMerchantUrl;
    }
    public void setSubMerchantUrl(String subMerchantUrl) {
        this.subMerchantUrl = subMerchantUrl;
    }
    public String getSubMerchanteCheckBillingDescriptor() {
        return subMerchanteCheckBillingDescriptor;
    }
    public void setSubMerchanteCheckBillingDescriptor(
            String subMerchanteCheckBillingDescriptor) {
        this.subMerchanteCheckBillingDescriptor = subMerchanteCheckBillingDescriptor;
    }
    public String getSubMerchanteCheckCompanyName() {
        return subMerchanteCheckCompanyName;
    }
    public void setSubMerchanteCheckCompanyName(String subMerchanteCheckCompanyName) {
        this.subMerchanteCheckCompanyName = subMerchanteCheckCompanyName;
    }

}