public class DescriptionDetails {
	private String codeOrScore;
	private String description;
	
	
    public String getCodeOrScore() {
        return codeOrScore;
    }
    public void setCodeOrScore(String codeOrScore) {
        this.codeOrScore = codeOrScore;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
	}

}