public class LegalEntityModel {
	
	// TODO Delete, class not used

	//Select options values
	private String legalEntityName;
    private String legalEntityType;
    private String legalEntityStreetAddress1;
    private String legalEntityStreetAddress2;
    private String legalEntityCity;
    private String legalEntityStateProvince;
    private String legalEntityPostalCode;
    private String legalEntityCountryCode;
    private String legalEntityFirstName;
    private String legalEntityLastName;
    private String legalEntityEmailAddress;
    private String legalEntityContactPhone;
    private String legalEntityDateOfBirth;
    private String legalEntityDriversLicense;
    private String legalEntityDriversLicenseState;
    private String legalEntitySsn;
    private String legalEntityTaxId;
    private String legalEntityIsExclusiveToPsp;
    private String legalEntityIsPciComplianceValidated;
    private String legalEntityPciLevel;
    private String legalEntityScanningVendor;
    private String legalEntityQualifiedSecurityAssessor;
    private String legalEntityMostRecentlyPassedScan;
    private String legalEntityReportOnCompliance;
    private String legalEntityAnnualCreditCardSalesVolume;
    private String legalEntityHasAcceptedCreditCards;
    
    public String getLegalEntityName() {
        return legalEntityName;
    }

    public void setLegalEntityName(String legalEntityName) {
        this.legalEntityName = legalEntityName;
    }

    public String getLegalEntityType() {
        return legalEntityType;
    }

    public void setLegalEntityType(String legalEntityType) {
        this.legalEntityType = legalEntityType;
    }

    public String getLegalEntityStreetAddress1() {
        return legalEntityStreetAddress1;
    }

    public void setLegalEntityStreetAddress1(String legalEntityStreetAddress1) {
        this.legalEntityStreetAddress1 = legalEntityStreetAddress1;
    }

    public String getLegalEntityStreetAddress2() {
        return legalEntityStreetAddress2;
    }

    public void setLegalEntityStreetAddress2(String legalEntityStreetAddress2) {
        this.legalEntityStreetAddress2 = legalEntityStreetAddress2;
    }

    public String getLegalEntityCity() {
        return legalEntityCity;
    }

    public void setLegalEntityCity(String legalEntityCity) {
        this.legalEntityCity = legalEntityCity;
    }

    public String getLegalEntityStateProvince() {
        return legalEntityStateProvince;
    }

    public void setLegalEntityStateProvince(String legalEntityStateProvince) {
        this.legalEntityStateProvince = legalEntityStateProvince;
    }

    public String getLegalEntityPostalCode() {
        return legalEntityPostalCode;
    }

    public void setLegalEntityPostalCode(String legalEntityPostalCode) {
        this.legalEntityPostalCode = legalEntityPostalCode;
    }

    public String getLegalEntityCountryCode() {
        return legalEntityCountryCode;
    }

    public void setLegalEntityCountryCode(String legalEntityCountryCode) {
        this.legalEntityCountryCode = legalEntityCountryCode;
    }

    public String getLegalEntityFirstName() {
        return legalEntityFirstName;
    }

    public void setLegalEntityFirstName(String legalEntityFirstName) {
        this.legalEntityFirstName = legalEntityFirstName;
    }

    public String getLegalEntityLastName() {
        return legalEntityLastName;
    }

    public void setLegalEntityLastName(String legalEntityLastName) {
        this.legalEntityLastName = legalEntityLastName;
    }

    public String getLegalEntityEmailAddress() {
        return legalEntityEmailAddress;
    }

    public void setLegalEntityEmailAddress(String legalEntityEmailAddress) {
        this.legalEntityEmailAddress = legalEntityEmailAddress;
    }

    public String getLegalEntityContactPhone() {
        return legalEntityContactPhone;
    }

    public void setLegalEntityContactPhone(String legalEntityContactPhone) {
        this.legalEntityContactPhone = legalEntityContactPhone;
    }

    public String getLegalEntityDateOfBirth() {
        return legalEntityDateOfBirth;
    }

    public void setLegalEntityDateOfBirth(String legalEntityDateOfBirth) {
        this.legalEntityDateOfBirth = legalEntityDateOfBirth;
    }

    public String getLegalEntityDriversLicense() {
        return legalEntityDriversLicense;
    }

    public void setLegalEntityDriversLicense(String legalEntityDriversLicense) {
        this.legalEntityDriversLicense = legalEntityDriversLicense;
    }

    public String getLegalEntityDriversLicenseState() {
        return legalEntityDriversLicenseState;
    }

    public void setLegalEntityDriversLicenseState(
            String legalEntityDriversLicenseState) {
        this.legalEntityDriversLicenseState = legalEntityDriversLicenseState;
    }

    public String getLegalEntitySsn() {
        return legalEntitySsn;
    }

    public void setLegalEntitySsn(String legalEntitySsn) {
        this.legalEntitySsn = legalEntitySsn;
    }

    public String getLegalEntityTaxId() {
        return legalEntityTaxId;
    }

    public void setLegalEntityTaxId(String legalEntityTaxId) {
        this.legalEntityTaxId = legalEntityTaxId;
    }

    public String getLegalEntityIsExclusiveToPsp() {
        return legalEntityIsExclusiveToPsp;
    }

    public void setLegalEntityIsExclusiveToPsp(
            String legalEntityIsExclusiveToPsp) {
        this.legalEntityIsExclusiveToPsp = legalEntityIsExclusiveToPsp;
    }

    public String getLegalEntityIsPciComplianceValidated() {
        return legalEntityIsPciComplianceValidated;
    }

    public void setLegalEntityIsPciComplianceValidated(
            String legalEntityIsPciComplianceValidated) {
        this.legalEntityIsPciComplianceValidated = legalEntityIsPciComplianceValidated;
    }

    public String getLegalEntityPciLevel() {
        return legalEntityPciLevel;
    }

    public void setLegalEntityPciLevel(String legalEntityPciLevel) {
        this.legalEntityPciLevel = legalEntityPciLevel;
    }

    public String getLegalEntityScanningVendor() {
        return legalEntityScanningVendor;
    }

    public void setLegalEntityScanningVendor(String legalEntityScanningVendor) {
        this.legalEntityScanningVendor = legalEntityScanningVendor;
    }

    public String getLegalEntityQualifiedSecurityAssessor() {
        return legalEntityQualifiedSecurityAssessor;
    }

    public void setLegalEntityQualifiedSecurityAssessor(
            String legalEntityQualifiedSecurityAssessor) {
        this.legalEntityQualifiedSecurityAssessor = legalEntityQualifiedSecurityAssessor;
    }

    public String getLegalEntityMostRecentlyPassedScan() {
        return legalEntityMostRecentlyPassedScan;
    }

    public void setLegalEntityMostRecentlyPassedScan(
            String legalEntityMostRecentlyPassedScan) {
        this.legalEntityMostRecentlyPassedScan = legalEntityMostRecentlyPassedScan;
    }

    public String getLegalEntityReportOnCompliance() {
        return legalEntityReportOnCompliance;
    }

    public void setLegalEntityReportOnCompliance(
            String legalEntityReportOnCompliance) {
        this.legalEntityReportOnCompliance = legalEntityReportOnCompliance;
    }

    public String getLegalEntityAnnualCreditCardSalesVolume() {
        return legalEntityAnnualCreditCardSalesVolume;
    }

    public void setLegalEntityAnnualCreditCardSalesVolume(
            String legalEntityAnnualCreditCardSalesVolume) {
        this.legalEntityAnnualCreditCardSalesVolume = legalEntityAnnualCreditCardSalesVolume;
    }

    public String getLegalEntityHasAcceptedCreditCards() {
        return legalEntityHasAcceptedCreditCards;
    }

    public void setLegalEntityHasAcceptedCreditCards(
            String legalEntityHasAcceptedCreditCards) {
        this.legalEntityHasAcceptedCreditCards = legalEntityHasAcceptedCreditCards;
    }
    
    /*
    // Default textbox values
	private String legalEntityNameDefault;
    private String legalEntityTypeDefault;
    private String legalEntityStreetAddress1Default;
    private String legalEntityStreetAddress2Default;
    private String legalEntityCityDefault;
    private String legalEntityStateProvinceDefault;
    private String legalEntityPostalCodeDefault;
    private String legalEntityCountryCodeDefault;
    private String legalEntityFirstNameDefault;
    private String legalEntityLastNameDefault;
    private String legalEntityEmailAddressDefault;
    private String legalEntityContactPhoneDefault;
    private String legalEntityDateOfBirthDefault;
    private String legalEntityDriversLicenseDefault;
    private String legalEntityDriversLicenseStateDefault;
    private String legalEntitySsnDefault;
    private String legalEntityTaxIdDefault;
    private String legalEntityIsExclusiveToPspDefault;
    private String legalEntityIsPciComplianceValidatedDefault;
    private String legalEntityPciLevelDefault;
    private String legalEntityScanningVendorDefault;
    private String legalEntityQualifiedSecurityAssessorDefault;
    private String legalEntityMostRecentlyPassedScanDefault;
    private String legalEntityReportOnComplianceDefault;
    private String legalEntityAnnualCreditCardSalesVolumeDefault;
    private String legalEntityHasAcceptedCreditCardsDefault;
    
    //Enabled-Disabled flags
        
    private Boolean isLegalEntityNameDefaultDisabled;
    private Boolean isLegalEntityTypeDefaultDisabled;
    private Boolean isLegalEntityStreetAddress1DefaultDisabled;
    private Boolean isLegalEntityStreetAddress2DefaultDisabled;
    private Boolean isLegalEntityCityDefaultDisabled;
    private Boolean isLegalEntityStateProvinceDefaultDisabled;
    private Boolean isLegalEntityPostalCodeDefaultDisabled;
    private Boolean isLegalEntityCountryCodeDefaultDisabled;
    private Boolean isLegalEntityFirstNameDefaultDisabled;
    private Boolean isLegalEntityLastNameDefaultDisabled;
    private Boolean isLegalEntityEmailAddressDefaultDisabled;
    private Boolean isLegalEntityContactPhoneDefaultDisabled;
    private Boolean isLegalEntityDateOfBirthDefaultDisabled;
    private Boolean isLegalEntityDriversLicenseDefaultDisabled;
    private Boolean isLegalEntityDriversLicenseStateDefaultDisabled;
    private Boolean isLegalEntitySsnDefaultDisabled;
    private Boolean isLegalEntityTaxIdDefaultDisabled;
    private Boolean isLegalEntityIsExclusiveToPspDefaultDisabled;
    private Boolean isLegalEntityIsPciComplianceValidatedDefaultDisabled;
    private Boolean isLegalEntityPciLevelDefaultDisabled;
    private Boolean isLegalEntityScanningVendorDefaultDisabled;
    private Boolean isLegalEntityQualifiedSecurityAssessorDefaultDisabled;
    private Boolean isLegalEntityMostRecentlyPassedScanDefaultDisabled;
    private Boolean isLegalEntityReportOnComplianceDefaultDisabled;
    private Boolean isLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled;
    private Boolean isLegalEntityHasAcceptedCreditCardsDefaultDisabled;
    
    public Boolean getIsLegalEntityNameDefaultDisabled() {
        return isLegalEntityNameDefaultDisabled;
    }
    public void setIsLegalEntityNameDefaultDisabled(
            Boolean isLegalEntityNameDefaultDisabled) {
        this.isLegalEntityNameDefaultDisabled = isLegalEntityNameDefaultDisabled;
    }
    public Boolean getIsLegalEntityTypeDefaultDisabled() {
        return isLegalEntityTypeDefaultDisabled;
    }
    public void setIsLegalEntityTypeDefaultDisabled(
            Boolean isLegalEntityTypeDefaultDisabled) {
        this.isLegalEntityTypeDefaultDisabled = isLegalEntityTypeDefaultDisabled;
    }
    public Boolean getIsLegalEntityStreetAddress1DefaultDisabled() {
        return isLegalEntityStreetAddress1DefaultDisabled;
    }
    public void setIsLegalEntityStreetAddress1DefaultDisabled(
            Boolean isLegalEntityStreetAddress1DefaultDisabled) {
        this.isLegalEntityStreetAddress1DefaultDisabled = isLegalEntityStreetAddress1DefaultDisabled;
    }
    public Boolean getIsLegalEntityStreetAddress2DefaultDisabled() {
        return isLegalEntityStreetAddress2DefaultDisabled;
    }
    public void setIsLegalEntityStreetAddress2DefaultDisabled(
            Boolean isLegalEntityStreetAddress2DefaultDisabled) {
        this.isLegalEntityStreetAddress2DefaultDisabled = isLegalEntityStreetAddress2DefaultDisabled;
    }
    public Boolean getIsLegalEntityCityDefaultDisabled() {
        return isLegalEntityCityDefaultDisabled;
    }
    public void setIsLegalEntityCityDefaultDisabled(
            Boolean isLegalEntityCityDefaultDisabled) {
        this.isLegalEntityCityDefaultDisabled = isLegalEntityCityDefaultDisabled;
    }
    public Boolean getIsLegalEntityStateProvinceDefaultDisabled() {
        return isLegalEntityStateProvinceDefaultDisabled;
    }
    public void setIsLegalEntityStateProvinceDefaultDisabled(
            Boolean isLegalEntityStateProvinceDefaultDisabled) {
        this.isLegalEntityStateProvinceDefaultDisabled = isLegalEntityStateProvinceDefaultDisabled;
    }
    public Boolean getIsLegalEntityPostalCodeDefaultDisabled() {
        return isLegalEntityPostalCodeDefaultDisabled;
    }
    public void setIsLegalEntityPostalCodeDefaultDisabled(
            Boolean isLegalEntityPostalCodeDefaultDisabled) {
        this.isLegalEntityPostalCodeDefaultDisabled = isLegalEntityPostalCodeDefaultDisabled;
    }
    public Boolean getIsLegalEntityCountryCodeDefaultDisabled() {
        return isLegalEntityCountryCodeDefaultDisabled;
    }
    public void setIsLegalEntityCountryCodeDefaultDisabled(
            Boolean isLegalEntityCountryCodeDefaultDisabled) {
        this.isLegalEntityCountryCodeDefaultDisabled = isLegalEntityCountryCodeDefaultDisabled;
    }
    public Boolean getIsLegalEntityFirstNameDefaultDisabled() {
        return isLegalEntityFirstNameDefaultDisabled;
    }
    public void setIsLegalEntityFirstNameDefaultDisabled(
            Boolean isLegalEntityFirstNameDefaultDisabled) {
        this.isLegalEntityFirstNameDefaultDisabled = isLegalEntityFirstNameDefaultDisabled;
    }
    public Boolean getIsLegalEntityLastNameDefaultDisabled() {
        return isLegalEntityLastNameDefaultDisabled;
    }
    public void setIsLegalEntityLastNameDefaultDisabled(
            Boolean isLegalEntityLastNameDefaultDisabled) {
        this.isLegalEntityLastNameDefaultDisabled = isLegalEntityLastNameDefaultDisabled;
    }
    public Boolean getIsLegalEntityEmailAddressDefaultDisabled() {
        return isLegalEntityEmailAddressDefaultDisabled;
    }
    public void setIsLegalEntityEmailAddressDefaultDisabled(
            Boolean isLegalEntityEmailAddressDefaultDisabled) {
        this.isLegalEntityEmailAddressDefaultDisabled = isLegalEntityEmailAddressDefaultDisabled;
    }
    public Boolean getIsLegalEntityContactPhoneDefaultDisabled() {
        return isLegalEntityContactPhoneDefaultDisabled;
    }
    public void setIsLegalEntityContactPhoneDefaultDisabled(
            Boolean isLegalEntityContactPhoneDefaultDisabled) {
        this.isLegalEntityContactPhoneDefaultDisabled = isLegalEntityContactPhoneDefaultDisabled;
    }
    public Boolean getIsLegalEntityDateOfBirthDefaultDisabled() {
        return isLegalEntityDateOfBirthDefaultDisabled;
    }
    public void setIsLegalEntityDateOfBirthDefaultDisabled(
            Boolean isLegalEntityDateOfBirthDefaultDisabled) {
        this.isLegalEntityDateOfBirthDefaultDisabled = isLegalEntityDateOfBirthDefaultDisabled;
    }
    public Boolean getIsLegalEntityDriversLicenseDefaultDisabled() {
        return isLegalEntityDriversLicenseDefaultDisabled;
    }
    public void setIsLegalEntityDriversLicenseDefaultDisabled(
            Boolean isLegalEntityDriversLicenseDefaultDisabled) {
        this.isLegalEntityDriversLicenseDefaultDisabled = isLegalEntityDriversLicenseDefaultDisabled;
    }
    public Boolean getIsLegalEntityDriversLicenseStateDefaultDisabled() {
        return isLegalEntityDriversLicenseStateDefaultDisabled;
    }
    public void setIsLegalEntityDriversLicenseStateDefaultDisabled(
            Boolean isLegalEntityDriversLicenseStateDefaultDisabled) {
        this.isLegalEntityDriversLicenseStateDefaultDisabled = isLegalEntityDriversLicenseStateDefaultDisabled;
    }
    public Boolean getIsLegalEntitySsnDefaultDisabled() {
        return isLegalEntitySsnDefaultDisabled;
    }
    public void setIsLegalEntitySsnDefaultDisabled(
            Boolean isLegalEntitySsnDefaultDisabled) {
        this.isLegalEntitySsnDefaultDisabled = isLegalEntitySsnDefaultDisabled;
    }
    public Boolean getIsLegalEntityTaxIdDefaultDisabled() {
        return isLegalEntityTaxIdDefaultDisabled;
    }
    public void setIsLegalEntityTaxIdDefaultDisabled(
            Boolean isLegalEntityTaxIdDefaultDisabled) {
        this.isLegalEntityTaxIdDefaultDisabled = isLegalEntityTaxIdDefaultDisabled;
    }
    public Boolean getIsLegalEntityIsExclusiveToPspDefaultDisabled() {
        return isLegalEntityIsExclusiveToPspDefaultDisabled;
    }
    public void setIsLegalEntityIsExclusiveToPspDefaultDisabled(
            Boolean isLegalEntityIsExclusiveToPspDefaultDisabled) {
        this.isLegalEntityIsExclusiveToPspDefaultDisabled = isLegalEntityIsExclusiveToPspDefaultDisabled;
    }
    public Boolean getIsLegalEntityIsPciComplianceValidatedDefaultDisabled() {
        return isLegalEntityIsPciComplianceValidatedDefaultDisabled;
    }
    public void setIsLegalEntityIsPciComplianceValidatedDefaultDisabled(
            Boolean isLegalEntityIsPciComplianceValidatedDefaultDisabled) {
        this.isLegalEntityIsPciComplianceValidatedDefaultDisabled = isLegalEntityIsPciComplianceValidatedDefaultDisabled;
    }
    public Boolean getIsLegalEntityPciLevelDefaultDisabled() {
        return isLegalEntityPciLevelDefaultDisabled;
    }
    public void setIsLegalEntityPciLevelDefaultDisabled(
            Boolean isLegalEntityPciLevelDefaultDisabled) {
        this.isLegalEntityPciLevelDefaultDisabled = isLegalEntityPciLevelDefaultDisabled;
    }
    public Boolean getIsLegalEntityScanningVendorDefaultDisabled() {
        return isLegalEntityScanningVendorDefaultDisabled;
    }
    public void setIsLegalEntityScanningVendorDefaultDisabled(
            Boolean isLegalEntityScanningVendorDefaultDisabled) {
        this.isLegalEntityScanningVendorDefaultDisabled = isLegalEntityScanningVendorDefaultDisabled;
    }
    public Boolean getIsLegalEntityQualifiedSecurityAssessorDefaultDisabled() {
        return isLegalEntityQualifiedSecurityAssessorDefaultDisabled;
    }
    public void setIsLegalEntityQualifiedSecurityAssessorDefaultDisabled(
            Boolean isLegalEntityQualifiedSecurityAssessorDefaultDisabled) {
        this.isLegalEntityQualifiedSecurityAssessorDefaultDisabled = isLegalEntityQualifiedSecurityAssessorDefaultDisabled;
    }
    public Boolean getIsLegalEntityMostRecentlyPassedScanDefaultDisabled() {
        return isLegalEntityMostRecentlyPassedScanDefaultDisabled;
    }
    public void setIsLegalEntityMostRecentlyPassedScanDefaultDisabled(
            Boolean isLegalEntityMostRecentlyPassedScanDefaultDisabled) {
        this.isLegalEntityMostRecentlyPassedScanDefaultDisabled = isLegalEntityMostRecentlyPassedScanDefaultDisabled;
    }
    public Boolean getIsLegalEntityReportOnComplianceDefaultDisabled() {
        return isLegalEntityReportOnComplianceDefaultDisabled;
    }
    public void setIsLegalEntityReportOnComplianceDefaultDisabled(
            Boolean isLegalEntityReportOnComplianceDefaultDisabled) {
        this.isLegalEntityReportOnComplianceDefaultDisabled = isLegalEntityReportOnComplianceDefaultDisabled;
    }
    public Boolean getIsLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled() {
        return isLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled;
    }
    public void setIsLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled(
            Boolean isLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled) {
        this.isLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled = isLegalEntityAnnualCreditCardSalesVolumeDefaultDisabled;
    }
    public Boolean getIsLegalEntityHasAcceptedCreditCardsDefaultDisabled() {
        return isLegalEntityHasAcceptedCreditCardsDefaultDisabled;
    }
    public void setIsLegalEntityHasAcceptedCreditCardsDefaultDisabled(
            Boolean isLegalEntityHasAcceptedCreditCardsDefaultDisabled) {
        this.isLegalEntityHasAcceptedCreditCardsDefaultDisabled = isLegalEntityHasAcceptedCreditCardsDefaultDisabled;
    }
    
    public String getLegalEntityNameDefault() {
        return legalEntityNameDefault;
    }
    public void setLegalEntityNameDefault(String legalEntityNameDefault) {
        this.legalEntityNameDefault = legalEntityNameDefault;
    }
    public String getLegalEntityTypeDefault() {
        return legalEntityTypeDefault;
    }
    public void setLegalEntityTypeDefault(String legalEntityTypeDefault) {
        this.legalEntityTypeDefault = legalEntityTypeDefault;
    }
    public String getLegalEntityStreetAddress1Default() {
        return legalEntityStreetAddress1Default;
    }
    public void setLegalEntityStreetAddress1Default(
            String legalEntityStreetAddress1Default) {
        this.legalEntityStreetAddress1Default = legalEntityStreetAddress1Default;
    }
    public String getLegalEntityStreetAddress2Default() {
        return legalEntityStreetAddress2Default;
    }
    public void setLegalEntityStreetAddress2Default(
            String legalEntityStreetAddress2Default) {
        this.legalEntityStreetAddress2Default = legalEntityStreetAddress2Default;
    }
    public String getLegalEntityCityDefault() {
        return legalEntityCityDefault;
    }
    public void setLegalEntityCityDefault(String legalEntityCityDefault) {
        this.legalEntityCityDefault = legalEntityCityDefault;
    }
    public String getLegalEntityStateProvinceDefault() {
        return legalEntityStateProvinceDefault;
    }
    public void setLegalEntityStateProvinceDefault(
            String legalEntityStateProvinceDefault) {
        this.legalEntityStateProvinceDefault = legalEntityStateProvinceDefault;
    }
    public String getLegalEntityPostalCodeDefault() {
        return legalEntityPostalCodeDefault;
    }
    public void setLegalEntityPostalCodeDefault(String legalEntityPostalCodeDefault) {
        this.legalEntityPostalCodeDefault = legalEntityPostalCodeDefault;
    }
    public String getLegalEntityCountryCodeDefault() {
        return legalEntityCountryCodeDefault;
    }
    public void setLegalEntityCountryCodeDefault(
            String legalEntityCountryCodeDefault) {
        this.legalEntityCountryCodeDefault = legalEntityCountryCodeDefault;
    }
    public String getLegalEntityFirstNameDefault() {
        return legalEntityFirstNameDefault;
    }
    public void setLegalEntityFirstNameDefault(String legalEntityFirstNameDefault) {
        this.legalEntityFirstNameDefault = legalEntityFirstNameDefault;
    }
    public String getLegalEntityLastNameDefault() {
        return legalEntityLastNameDefault;
    }
    public void setLegalEntityLastNameDefault(String legalEntityLastNameDefault) {
        this.legalEntityLastNameDefault = legalEntityLastNameDefault;
    }
    public String getLegalEntityEmailAddressDefault() {
        return legalEntityEmailAddressDefault;
    }
    public void setLegalEntityEmailAddressDefault(
            String legalEntityEmailAddressDefault) {
        this.legalEntityEmailAddressDefault = legalEntityEmailAddressDefault;
    }
    public String getLegalEntityContactPhoneDefault() {
        return legalEntityContactPhoneDefault;
    }
    public void setLegalEntityContactPhoneDefault(
            String legalEntityContactPhoneDefault) {
        this.legalEntityContactPhoneDefault = legalEntityContactPhoneDefault;
    }
    public String getLegalEntityDateOfBirthDefault() {
        return legalEntityDateOfBirthDefault;
    }
    public void setLegalEntityDateOfBirthDefault(
            String legalEntityDateOfBirthDefault) {
        this.legalEntityDateOfBirthDefault = legalEntityDateOfBirthDefault;
    }
    public String getLegalEntityDriversLicenseDefault() {
        return legalEntityDriversLicenseDefault;
    }
    public void setLegalEntityDriversLicenseDefault(
            String legalEntityDriversLicenseDefault) {
        this.legalEntityDriversLicenseDefault = legalEntityDriversLicenseDefault;
    }
    public String getLegalEntityDriversLicenseStateDefault() {
        return legalEntityDriversLicenseStateDefault;
    }
    public void setLegalEntityDriversLicenseStateDefault(
            String legalEntityDriversLicenseStateDefault) {
        this.legalEntityDriversLicenseStateDefault = legalEntityDriversLicenseStateDefault;
    }
    public String getLegalEntitySsnDefault() {
        return legalEntitySsnDefault;
    }
    public void setLegalEntitySsnDefault(String legalEntitySsnDefault) {
        this.legalEntitySsnDefault = legalEntitySsnDefault;
    }
    public String getLegalEntityTaxIdDefault() {
        return legalEntityTaxIdDefault;
    }
    public void setLegalEntityTaxIdDefault(String legalEntityTaxIdDefault) {
        this.legalEntityTaxIdDefault = legalEntityTaxIdDefault;
    }
    public String getLegalEntityIsExclusiveToPspDefault() {
        return legalEntityIsExclusiveToPspDefault;
    }
    public void setLegalEntityIsExclusiveToPspDefault(
            String legalEntityIsExclusiveToPspDefault) {
        this.legalEntityIsExclusiveToPspDefault = legalEntityIsExclusiveToPspDefault;
    }
    public String getLegalEntityIsPciComplianceValidatedDefault() {
        return legalEntityIsPciComplianceValidatedDefault;
    }
    public void setLegalEntityIsPciComplianceValidatedDefault(
            String legalEntityIsPciComplianceValidatedDefault) {
        this.legalEntityIsPciComplianceValidatedDefault = legalEntityIsPciComplianceValidatedDefault;
    }
    public String getLegalEntityPciLevelDefault() {
        return legalEntityPciLevelDefault;
    }
    public void setLegalEntityPciLevelDefault(String legalEntityPciLevelDefault) {
        this.legalEntityPciLevelDefault = legalEntityPciLevelDefault;
    }
    public String getLegalEntityScanningVendorDefault() {
        return legalEntityScanningVendorDefault;
    }
    public void setLegalEntityScanningVendorDefault(
            String legalEntityScanningVendorDefault) {
        this.legalEntityScanningVendorDefault = legalEntityScanningVendorDefault;
    }
    public String getLegalEntityQualifiedSecurityAssessorDefault() {
        return legalEntityQualifiedSecurityAssessorDefault;
    }
    public void setLegalEntityQualifiedSecurityAssessorDefault(
            String legalEntityQualifiedSecurityAssessorDefault) {
        this.legalEntityQualifiedSecurityAssessorDefault = legalEntityQualifiedSecurityAssessorDefault;
    }
    public String getLegalEntityMostRecentlyPassedScanDefault() {
        return legalEntityMostRecentlyPassedScanDefault;
    }
    public void setLegalEntityMostRecentlyPassedScanDefault(
            String legalEntityMostRecentlyPassedScanDefault) {
        this.legalEntityMostRecentlyPassedScanDefault = legalEntityMostRecentlyPassedScanDefault;
    }
    public String getLegalEntityReportOnComplianceDefault() {
        return legalEntityReportOnComplianceDefault;
    }
    public void setLegalEntityReportOnComplianceDefault(
            String legalEntityReportOnComplianceDefault) {
        this.legalEntityReportOnComplianceDefault = legalEntityReportOnComplianceDefault;
    }
    public String getLegalEntityAnnualCreditCardSalesVolumeDefault() {
        return legalEntityAnnualCreditCardSalesVolumeDefault;
    }
    public void setLegalEntityAnnualCreditCardSalesVolumeDefault(
            String legalEntityAnnualCreditCardSalesVolumeDefault) {
        this.legalEntityAnnualCreditCardSalesVolumeDefault = legalEntityAnnualCreditCardSalesVolumeDefault;
    }
    public String getLegalEntityHasAcceptedCreditCardsDefault() {
        return legalEntityHasAcceptedCreditCardsDefault;
    }
    public void setLegalEntityHasAcceptedCreditCardsDefault(
            String legalEntityHasAcceptedCreditCardsDefault) {
        this.legalEntityHasAcceptedCreditCardsDefault = legalEntityHasAcceptedCreditCardsDefault;
    }
    */
    
}