public class LienResult {
	private String lienyType;
	private String releasedCount;
	private String unreleasedCount;
	private String companyName;
	private String streetAddress1;
	private String streetAddress2;
	private String city;
	private String state;
	private String zip;
	private String zip4;
	private String filingDate;
	
	public String getLienyType() {
        return lienyType;
    }
    public void setLienyType(String lienyType) {
        this.lienyType = lienyType;
    }
    public String getReleasedCount() {
        return releasedCount;
    }
    public void setReleasedCount(String releasedCount) {
        this.releasedCount = releasedCount;
    }
    public String getUnreleasedCount() {
        return unreleasedCount;
    }
    public void setUnreleasedCount(String unreleasedCount) {
        this.unreleasedCount = unreleasedCount;
    }
    public String getCompanyName() {
        return companyName;
    }
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getStreetAddress1() {
        return streetAddress1;
    }
    public void setStreetAddress1(String streetAddress1) {
        this.streetAddress1 = streetAddress1;
    }
    public String getStreetAddress2() {
        return streetAddress2;
    }
    public void setStreetAddress2(String streetAddress2) {
        this.streetAddress2 = streetAddress2;
    }
    public String getCity() {
        return city;
    }
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return state;
    }
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return zip;
    }
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getZip4() {
        return zip4;
    }
    public void setZip4(String zip4) {
        this.zip4 = zip4;
    }
    public String getFilingDate() {
        return filingDate;
    }
    public void setFilingDate(String filingDate) {
        this.filingDate = filingDate;
    }

}