public class LitleRequestXml {
	private String createLegalEntityRequest;
	private String createSubMerchantRequest;
	
	public LitleRequestXml(){
		
	}
	
	public void setCreateLegalEntityRequest(String createLegalEntityRequest){
		this.createLegalEntityRequest = createLegalEntityRequest;
	}
	
	public String getCreateLegalEntityRequest(){
		return createLegalEntityRequest;
	}
	
	public void setCreateSubMerchantRequest(String createSubMerchantRequest){
		this.createSubMerchantRequest = createSubMerchantRequest;
	}
	
	public String getCreateSubMerchantRequest(){
		return createSubMerchantRequest;
	}

}