public class SubMerchantModel {
	
    private Address subMerchantAddress;
    private String subMerchantAmexMid;
    private String subMerchantBankAccountNumber;
    private String subMerchantBankRoutingNumber;
    private String subMerchantCreateCredentials;
    private String subMerchantCustomerServiceNumber;
    private String subMerchantDiscoverConveyMid;
    private String subMerchantHardCodeBillingDescriptor;
    private String subMerchantMaxTransactionAmount;
    private String subMerchantMerchantCategoryCode;
    private String subMerchantMerchantName;
    private PrimaryContact subMerchantPrimaryContact;
    private String subMerchantPspMerchantId;
    private String subMerchantUrl;
    private String subMerchanteCheckBillingDescriptor;
    private String subMerchanteCheckCompanyName;
    private Boolean isSubMerchantAmexMidFromOpportunity;
    private Boolean isSubMerchantBankAccountNumberFromOpportunity;
    private Boolean isSubMerchantBankRoutingNumberFromOpportunity;
    private Boolean isSubMerchantCreateCredentialsFromOpportunity;
    private Boolean isSubMerchantCustomerServiceNumberFromOpportunity;
    private Boolean isSubMerchantDiscoverConveyMidFromOpportunity;
    private Boolean isSubMerchantHardCodeBillingDescriptorFromOpportunity;
    private Boolean isSubMerchantMaxTransactionAmountFromOpportunity;
    private Boolean isSubMerchantMerchantCategoryCodeFromOpportunity;
    private Boolean isSubMerchantMerchantNameFromOpportunity;
    private Boolean isSubMerchantPspMerchantIdFromOpportunity;
    private Boolean isSubMerchantUrlFromOpportunity;
    private Boolean isSubMerchanteCheckBillingDescriptorFromOpportunity;
    private Boolean isSubMerchanteCheckCompanyNameFromOpportunity;
    
    public SubMerchantModel(){
    	subMerchantAddress = new Address();
    	subMerchantPrimaryContact = new PrimaryContact();
	    isSubMerchantAmexMidFromOpportunity = false;
	    isSubMerchantBankAccountNumberFromOpportunity = false;
	    isSubMerchantBankRoutingNumberFromOpportunity = false;
	    isSubMerchantCreateCredentialsFromOpportunity = false;
	    isSubMerchantCustomerServiceNumberFromOpportunity = false;
	    isSubMerchantDiscoverConveyMidFromOpportunity = false;
	    isSubMerchantHardCodeBillingDescriptorFromOpportunity = false;
	    isSubMerchantMaxTransactionAmountFromOpportunity = false;
	    isSubMerchantMerchantCategoryCodeFromOpportunity = false;
	    isSubMerchantMerchantNameFromOpportunity = false;
	    isSubMerchantPspMerchantIdFromOpportunity = false;
	    isSubMerchantUrlFromOpportunity = false;
	    isSubMerchanteCheckBillingDescriptorFromOpportunity = false;
	    isSubMerchanteCheckCompanyNameFromOpportunity = false;
    }
    
    
    public Address getSubMerchantAddress() {
        return subMerchantAddress;
    }
    public void setSubMerchantAddress(Address subMerchantAddress) {
        this.subMerchantAddress = subMerchantAddress;
    }
    public String getSubMerchantAmexMid() {
        return subMerchantAmexMid;
    }
    public void setSubMerchantAmexMid(String subMerchantAmexMid) {
        this.subMerchantAmexMid = subMerchantAmexMid;
    }
    public String getSubMerchantBankAccountNumber() {
        return subMerchantBankAccountNumber;
    }
    public void setSubMerchantBankAccountNumber(String subMerchantBankAccountNumber) {
        this.subMerchantBankAccountNumber = subMerchantBankAccountNumber;
    }
    public String getSubMerchantBankRoutingNumber() {
        return subMerchantBankRoutingNumber;
    }
    public void setSubMerchantBankRoutingNumber(String subMerchantBankRoutingNumber) {
        this.subMerchantBankRoutingNumber = subMerchantBankRoutingNumber;
    }
    public String getSubMerchantCreateCredentials() {
        return subMerchantCreateCredentials;
    }
    public void setSubMerchantCreateCredentials(String subMerchantCreateCredentials) {
        this.subMerchantCreateCredentials = subMerchantCreateCredentials;
    }
    public String getSubMerchantCustomerServiceNumber() {
        return subMerchantCustomerServiceNumber;
    }
    public void setSubMerchantCustomerServiceNumber(
            String subMerchantCustomerServiceNumber) {
        this.subMerchantCustomerServiceNumber = subMerchantCustomerServiceNumber;
    }
    public String getSubMerchantDiscoverConveyMid() {
        return subMerchantDiscoverConveyMid;
    }
    public void setSubMerchantDiscoverConveyMid(String subMerchantDiscoverConveyMid) {
        this.subMerchantDiscoverConveyMid = subMerchantDiscoverConveyMid;
    }
    public String getSubMerchantHardCodeBillingDescriptor() {
        return subMerchantHardCodeBillingDescriptor;
    }
    public void setSubMerchantHardCodeBillingDescriptor(
            String subMerchantHardCodeBillingDescriptor) {
        this.subMerchantHardCodeBillingDescriptor = subMerchantHardCodeBillingDescriptor;
    }
    public String getSubMerchantMaxTransactionAmount() {
        return subMerchantMaxTransactionAmount;
    }
    public void setSubMerchantMaxTransactionAmount(
            String subMerchantMaxTransactionAmount) {
        this.subMerchantMaxTransactionAmount = subMerchantMaxTransactionAmount;
    }
    public String getSubMerchantMerchantCategoryCode() {
        return subMerchantMerchantCategoryCode;
    }
    public void setSubMerchantMerchantCategoryCode(
            String subMerchantMerchantCategoryCode) {
        this.subMerchantMerchantCategoryCode = subMerchantMerchantCategoryCode;
    }
    public String getSubMerchantMerchantName() {
        return subMerchantMerchantName;
    }
    public void setSubMerchantMerchantName(String subMerchantMerchantName) {
        this.subMerchantMerchantName = subMerchantMerchantName;
    }
    public PrimaryContact getSubMerchantPrimaryContact() {
        return subMerchantPrimaryContact;
    }
    public void setSubMerchantPrimaryContact(
            PrimaryContact subMerchantPrimaryContact) {
        this.subMerchantPrimaryContact = subMerchantPrimaryContact;
    }
    public String getSubMerchantPspMerchantId() {
        return subMerchantPspMerchantId;
    }
    public void setSubMerchantPspMerchantId(String subMerchantPspMerchantId) {
        this.subMerchantPspMerchantId = subMerchantPspMerchantId;
    }
    public String getSubMerchantUrl() {
        return subMerchantUrl;
    }
    public void setSubMerchantUrl(String subMerchantUrl) {
        this.subMerchantUrl = subMerchantUrl;
    }
    public String getSubMerchanteCheckBillingDescriptor() {
        return subMerchanteCheckBillingDescriptor;
    }
    public void setSubMerchanteCheckBillingDescriptor(
            String subMerchanteCheckBillingDescriptor) {
        this.subMerchanteCheckBillingDescriptor = subMerchanteCheckBillingDescriptor;
    }
    public String getSubMerchanteCheckCompanyName() {
        return subMerchanteCheckCompanyName;
    }
    public void setSubMerchanteCheckCompanyName(String subMerchanteCheckCompanyName) {
        this.subMerchanteCheckCompanyName = subMerchanteCheckCompanyName;
    }
    public Boolean getIsSubMerchantAmexMidFromOpportunity() {
        return isSubMerchantAmexMidFromOpportunity;
    }
    public void setIsSubMerchantAmexMidFromOpportunity(
            Boolean isSubMerchantAmexMidFromOpportunity) {
        this.isSubMerchantAmexMidFromOpportunity = isSubMerchantAmexMidFromOpportunity;
    }
    public Boolean getIsSubMerchantBankAccountNumberFromOpportunity() {
        return isSubMerchantBankAccountNumberFromOpportunity;
    }
    public void setIsSubMerchantBankAccountNumberFromOpportunity(
            Boolean isSubMerchantBankAccountNumberFromOpportunity) {
        this.isSubMerchantBankAccountNumberFromOpportunity = isSubMerchantBankAccountNumberFromOpportunity;
    }
    public Boolean getIsSubMerchantBankRoutingNumberFromOpportunity() {
        return isSubMerchantBankRoutingNumberFromOpportunity;
    }
    public void setIsSubMerchantBankRoutingNumberFromOpportunity(
            Boolean isSubMerchantBankRoutingNumberFromOpportunity) {
        this.isSubMerchantBankRoutingNumberFromOpportunity = isSubMerchantBankRoutingNumberFromOpportunity;
    }
    public Boolean getIsSubMerchantCreateCredentialsFromOpportunity() {
        return isSubMerchantCreateCredentialsFromOpportunity;
    }
    public void setIsSubMerchantCreateCredentialsFromOpportunity(
            Boolean isSubMerchantCreateCredentialsFromOpportunity) {
        this.isSubMerchantCreateCredentialsFromOpportunity = isSubMerchantCreateCredentialsFromOpportunity;
    }
    public Boolean getIsSubMerchantCustomerServiceNumberFromOpportunity() {
        return isSubMerchantCustomerServiceNumberFromOpportunity;
    }
    public void setIsSubMerchantCustomerServiceNumberFromOpportunity(
            Boolean isSubMerchantCustomerServiceNumberFromOpportunity) {
        this.isSubMerchantCustomerServiceNumberFromOpportunity = isSubMerchantCustomerServiceNumberFromOpportunity;
    }
    public Boolean getIsSubMerchantDiscoverConveyMidFromOpportunity() {
        return isSubMerchantDiscoverConveyMidFromOpportunity;
    }
    public void setIsSubMerchantDiscoverConveyMidFromOpportunity(
            Boolean isSubMerchantDiscoverConveyMidFromOpportunity) {
        this.isSubMerchantDiscoverConveyMidFromOpportunity = isSubMerchantDiscoverConveyMidFromOpportunity;
    }
    public Boolean getIsSubMerchantHardCodeBillingDescriptorFromOpportunity() {
        return isSubMerchantHardCodeBillingDescriptorFromOpportunity;
    }
    public void setIsSubMerchantHardCodeBillingDescriptorFromOpportunity(
            Boolean isSubMerchantHardCodeBillingDescriptorFromOpportunity) {
        this.isSubMerchantHardCodeBillingDescriptorFromOpportunity = isSubMerchantHardCodeBillingDescriptorFromOpportunity;
    }
    public Boolean getIsSubMerchantMaxTransactionAmountFromOpportunity() {
        return isSubMerchantMaxTransactionAmountFromOpportunity;
    }
    public void setIsSubMerchantMaxTransactionAmountFromOpportunity(
            Boolean isSubMerchantMaxTransactionAmountFromOpportunity) {
        this.isSubMerchantMaxTransactionAmountFromOpportunity = isSubMerchantMaxTransactionAmountFromOpportunity;
    }
    public Boolean getIsSubMerchantMerchantCategoryCodeFromOpportunity() {
        return isSubMerchantMerchantCategoryCodeFromOpportunity;
    }
    public void setIsSubMerchantMerchantCategoryCodeFromOpportunity(
            Boolean isSubMerchantMerchantCategoryCodeFromOpportunity) {
        this.isSubMerchantMerchantCategoryCodeFromOpportunity = isSubMerchantMerchantCategoryCodeFromOpportunity;
    }
    public Boolean getIsSubMerchantMerchantNameFromOpportunity() {
        return isSubMerchantMerchantNameFromOpportunity;
    }
    public void setIsSubMerchantMerchantNameFromOpportunity(
            Boolean isSubMerchantMerchantNameFromOpportunity) {
        this.isSubMerchantMerchantNameFromOpportunity = isSubMerchantMerchantNameFromOpportunity;
    }
    public Boolean getIsSubMerchantPspMerchantIdFromOpportunity() {
        return isSubMerchantPspMerchantIdFromOpportunity;
    }
    public void setIsSubMerchantPspMerchantIdFromOpportunity(
            Boolean isSubMerchantPspMerchantIdFromOpportunity) {
        this.isSubMerchantPspMerchantIdFromOpportunity = isSubMerchantPspMerchantIdFromOpportunity;
    }
    public Boolean getIsSubMerchantUrlFromOpportunity() {
        return isSubMerchantUrlFromOpportunity;
    }
    public void setIsSubMerchantUrlFromOpportunity(
            Boolean isSubMerchantUrlFromOpportunity) {
        this.isSubMerchantUrlFromOpportunity = isSubMerchantUrlFromOpportunity;
    }
    public Boolean getIsSubMerchanteCheckBillingDescriptorFromOpportunity() {
        return isSubMerchanteCheckBillingDescriptorFromOpportunity;
    }
    public void setIsSubMerchanteCheckBillingDescriptorFromOpportunity(
            Boolean isSubMerchanteCheckBillingDescriptorFromOpportunity) {
        this.isSubMerchanteCheckBillingDescriptorFromOpportunity = isSubMerchanteCheckBillingDescriptorFromOpportunity;
    }
    public Boolean getIsSubMerchanteCheckCompanyNameFromOpportunity() {
        return isSubMerchanteCheckCompanyNameFromOpportunity;
    }
    public void setIsSubMerchanteCheckCompanyNameFromOpportunity(
            Boolean isSubMerchanteCheckCompanyNameFromOpportunity) {
        this.isSubMerchanteCheckCompanyNameFromOpportunity = isSubMerchanteCheckCompanyNameFromOpportunity;
    }
}