/*
Copyright (c) 2013 Litle & Co.
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/
public class VerificationIndicators {
	private String nameVerified;
	private String addressVerified;
	private String cityVerified;
	private String zipVerified;
	private String phoneVerified;
	private String taxIdVerified;
	private String ssnVerified;
	private String dobVerified;
	
	
    public String getNameVerified() {
        return nameVerified;
    }
    public void setNameVerified(String nameVerified) {
        this.nameVerified = nameVerified;
    }
    public String getAddressVerified() {
        return addressVerified;
    }
    public void setAddressVerified(String addressVerified) {
        this.addressVerified = addressVerified;
    }
    public String getCityVerified() {
        return cityVerified;
    }
    public void setCityVerified(String cityVerified) {
        this.cityVerified = cityVerified;
    }
    public String getZipVerified() {
        return zipVerified;
    }
    public void setZipVerified(String zipVerified) {
        this.zipVerified = zipVerified;
    }
    public String getPhoneVerified() {
        return phoneVerified;
    }
    public void setPhoneVerified(String phoneVerified) {
        this.phoneVerified = phoneVerified;
    }
    public String getTaxIdVerified() {
        return taxIdVerified;
    }
    public void setTaxIdVerified(String taxIdVerified) {
        this.taxIdVerified = taxIdVerified;
    }
    
    public String getSsnVerified() {
        return ssnVerified;
    }
    public void setSsnVerified(String ssnVerified) {
        this.ssnVerified = ssnVerified;
    }
    
    public String getDobVerified() {
        return dobVerified;
    }
    public void setDobVerified(String dobVerified) {
        this.dobVerified = dobVerified;
    }

}