public class VerificationIndicators {
	private String nameVerfied;
	private String addressVerified;
	private String cityVerified;
	private String zipVerified;
	private String phoneVerified;
	private String taxIdVerified;
	private String ssnVerified;
	private String dobVerified;
	
	
    public String getNameVerfied() {
        return nameVerfied;
    }
    public void setNameVerfied(String nameVerfied) {
        this.nameVerfied = nameVerfied;
    }
    public String getAddressVerified() {
        return addressVerified;
    }
    public void setAddressVerified(String addressVerified) {
        this.addressVerified = addressVerified;
    }
    public String getCityVerified() {
        return cityVerified;
    }
    public void setCityVerified(String cityVerified) {
        this.cityVerified = cityVerified;
    }
    public String getZipVerified() {
        return zipVerified;
    }
    public void setZipVerified(String zipVerified) {
        this.zipVerified = zipVerified;
    }
    public String getPhoneVerified() {
        return phoneVerified;
    }
    public void setPhoneVerified(String phoneVerified) {
        this.phoneVerified = phoneVerified;
    }
    public String getTaxIdVerified() {
        return taxIdVerified;
    }
    public void setTaxIdVerified(String taxIdVerified) {
        this.taxIdVerified = taxIdVerified;
    }
    
    public String getSsnVerified() {
        return ssnVerified;
    }
    public void setSsnVerified(String ssnVerified) {
        this.ssnVerified = ssnVerified;
    }
    
    public String getDobVerified() {
        return dobVerified;
    }
    public void setDobVerified(String dobVerified) {
        this.dobVerified = dobVerified;
    }

}